enum ElementType: String {
    case grass
    case poison
    case fire
    case flying
    case water
    case bug
    case normal
    case electric
    case ground
    case fairy
    case psychic
    case rock
    case ice
    case dragon
    case dark
    case steel
    case fighting
    case ghost
}

struct Pokemon: Identifiable{
    var id: Int
    var name: String
    var types: [ElementType]
    var pokemonImage: String
    var defImage: String
}

let pokemons: [Pokemon] = [
    Pokemon(id: 1, name: "bulbasaur", types: [.grass, .poison], pokemonImage: "img_1", defImage: "IMG_2422"),
    Pokemon(id: 2, name: "ivysaur", types: [.grass, .poison], pokemonImage: "img_2", defImage: "IMG_2423"),
    Pokemon(id: 3, name: "venusaur", types: [.grass, .poison], pokemonImage: "img_3", defImage: "IMG_2424"),
    Pokemon(id: 4, name: "charmander", types: [.fire], pokemonImage: "img_4", defImage: "IMG_2425"),
    Pokemon(id: 5, name: "charmeleon", types: [.fire], pokemonImage: "img_5", defImage: "IMG_2426"),
    Pokemon(id: 6, name: "charizard", types: [.fire, .flying], pokemonImage: "img_6", defImage: "IMG_2427"),
    Pokemon(id: 7, name: "squirtle", types: [.water], pokemonImage: "img_7", defImage: "IMG_2428"),
    Pokemon(id: 8, name: "wartortle", types: [.water], pokemonImage: "img_8", defImage: "IMG_2429"),
    Pokemon(id: 9, name: "blastoise", types: [.water], pokemonImage: "img_9", defImage: "IMG_2430"),
    Pokemon(id: 10, name: "caterpie", types: [.bug], pokemonImage: "img_10", defImage: "IMG_2431"),
    Pokemon(id: 11, name: "metapod", types: [.bug], pokemonImage: "img_11", defImage: "IMG_2432"),
    Pokemon(id: 12, name: "butterfree", types: [.bug, .flying], pokemonImage: "img_12", defImage: "IMG_2433"),
    Pokemon(id: 13, name: "weedle", types: [.bug, .poison], pokemonImage: "img_13", defImage: "IMG_2434"),
    Pokemon(id: 14, name: "kakuna", types: [.bug, .poison], pokemonImage: "img_14", defImage: "IMG_2435"),
    Pokemon(id: 15, name: "beedrill", types: [.bug, .poison], pokemonImage: "img_15", defImage: "IMG_2436"),
    Pokemon(id: 16, name: "pidgey", types: [.normal, .flying], pokemonImage: "img_16", defImage: "IMG_2437"),
    Pokemon(id: 17, name: "pidgeotto", types: [.normal, .flying], pokemonImage: "img_17", defImage: "IMG_2438"),
    Pokemon(id: 18, name: "pidgeot", types: [.normal, .flying], pokemonImage: "img_18", defImage: "IMG_2439"),
    Pokemon(id: 19, name: "rattata", types: [.normal], pokemonImage: "img_19", defImage: "IMG_2440"),
    Pokemon(id: 20, name: "raticate", types: [.normal], pokemonImage: "img_20", defImage: "IMG_2441"),
    Pokemon(id: 21, name: "spearow", types: [.normal, .flying], pokemonImage: "img_21", defImage: "IMG_2442"),
    Pokemon(id: 22, name: "fearow", types: [.normal, .flying], pokemonImage: "img_22", defImage: "IMG_2443"),
    Pokemon(id: 23, name: "ekans", types: [.poison], pokemonImage: "img_23", defImage: "IMG_2444"),
    Pokemon(id: 24, name: "arbok", types: [.poison], pokemonImage: "img_24", defImage: "IMG_2445"),
    Pokemon(id: 25, name: "pikachu", types: [.electric], pokemonImage: "img_25", defImage: "IMG_2446"),
    Pokemon(id: 26, name: "raichu", types: [.electric], pokemonImage: "img_26", defImage: "IMG_2447"),
    Pokemon(id: 27, name: "sandshrew", types: [.ground], pokemonImage: "img_27", defImage: "IMG_2448"),
    Pokemon(id: 28, name: "sandslash", types: [.ground], pokemonImage: "img_28", defImage: "IMG_2449"),
    Pokemon(id: 29, name: "nidoran-f", types: [.poison], pokemonImage: "img_29", defImage: "IMG_2450"),
    Pokemon(id: 30, name: "nidorina", types: [.poison], pokemonImage: "img_30", defImage: "IMG_2451"),
    Pokemon(id: 31, name: "nidoqueen", types: [.poison, .ground], pokemonImage: "img_31", defImage: "IMG_2452"),
    Pokemon(id: 32, name: "nidoran-m", types: [.poison], pokemonImage: "img_32", defImage: "IMG_2453"),
    Pokemon(id: 33, name: "nidorino", types: [.poison], pokemonImage: "img_33", defImage: "IMG_2454"),
    Pokemon(id: 34, name: "nidoking", types: [.poison, .ground], pokemonImage: "img_34", defImage: "IMG_2455"),
    Pokemon(id: 35, name: "clefairy", types: [.fairy], pokemonImage: "img_35", defImage: "IMG_2456"),
    Pokemon(id: 36, name: "clefable", types: [.fairy], pokemonImage: "img_36", defImage: "IMG_2457"),
    Pokemon(id: 37, name: "vulpix", types: [.fire], pokemonImage: "img_37", defImage: "IMG_2458"),
    Pokemon(id: 38, name: "ninetales", types: [.fire], pokemonImage: "img_38", defImage: "IMG_2459"),
    Pokemon(id: 39, name: "jigglypuff", types: [.normal, .fairy], pokemonImage: "img_39", defImage: "IMG_2460"),
    Pokemon(id: 40, name: "wigglytuff", types: [.normal, .fairy], pokemonImage: "img_40", defImage: "IMG_2461"),
    Pokemon(id: 41, name: "zubat", types: [.poison, .flying], pokemonImage: "img_41", defImage: "IMG_2462"),
    Pokemon(id: 42, name: "golbat", types: [.poison, .flying], pokemonImage: "img_42", defImage: "IMG_2463"),
    Pokemon(id: 43, name: "oddish", types: [.grass, .poison], pokemonImage: "img_43", defImage: "IMG_2464"),
    Pokemon(id: 44, name: "gloom", types: [.grass, .poison], pokemonImage: "img_44", defImage: "IMG_2465"),
    Pokemon(id: 45, name: "vileplume", types: [.grass, .poison], pokemonImage: "img_45", defImage: "IMG_2466"),
    Pokemon(id: 46, name: "paras", types: [.bug, .grass], pokemonImage: "img_46", defImage: "IMG_2467"),
    Pokemon(id: 47, name: "parasect", types: [.bug, .grass], pokemonImage: "img_47", defImage: "IMG_2468"),
    Pokemon(id: 48, name: "venonat", types: [.bug, .poison], pokemonImage: "img_48", defImage: "IMG_2470"),
    Pokemon(id: 49, name: "venomoth", types: [.bug, .poison], pokemonImage: "img_49", defImage: "IMG_2471"),
    Pokemon(id: 50, name: "diglett", types: [.ground], pokemonImage: "img_50", defImage: "IMG_2472"),
    Pokemon(id: 51, name: "dugtrio", types: [.ground], pokemonImage: "img_51", defImage: "IMG_2473"),
    Pokemon(id: 52, name: "meowth", types: [.normal], pokemonImage: "img_52", defImage: "IMG_2474"),
    Pokemon(id: 53, name: "persian", types: [.normal], pokemonImage: "img_53", defImage: "IMG_2475"),
    Pokemon(id: 54, name: "psyduck", types: [.water], pokemonImage: "img_54", defImage: "IMG_2476"),
    Pokemon(id: 55, name: "golduck", types: [.water], pokemonImage: "img_55", defImage: "IMG_2477"),
    Pokemon(id: 56, name: "mankey", types: [.fighting], pokemonImage: "img_56", defImage: "IMG_2478"),
    Pokemon(id: 57, name: "primeape", types: [.fighting], pokemonImage: "img_57", defImage: "IMG_2479"),
    Pokemon(id: 58, name: "growlithe", types: [.fire], pokemonImage: "img_58", defImage: "IMG_2480"),
    Pokemon(id: 59, name: "arcanine", types: [.fire], pokemonImage: "img_59", defImage: "IMG_2481"),
    Pokemon(id: 60, name: "poliwag", types: [.water], pokemonImage: "img_60", defImage: "IMG_2482"),
    Pokemon(id: 61, name: "poliwhirl", types: [.water], pokemonImage: "img_61", defImage: "IMG_2483"),
    Pokemon(id: 62, name: "poliwrath", types: [.water, .fighting], pokemonImage: "img_62", defImage: "IMG_2484"),
    Pokemon(id: 63, name: "abra", types: [.psychic], pokemonImage: "img_63", defImage: "IMG_2485"),
    Pokemon(id: 64, name: "kadabra", types: [.psychic], pokemonImage: "img_64", defImage: "IMG_2486"),
    Pokemon(id: 65, name: "alakazam", types: [.psychic], pokemonImage: "img_65", defImage: "IMG_2487"),
    Pokemon(id: 66, name: "machop", types: [.fighting], pokemonImage: "img_66", defImage: "IMG_2488"),
    Pokemon(id: 67, name: "machoke", types: [.fighting], pokemonImage: "img_67", defImage: "IMG_2489"),
    Pokemon(id: 68, name: "machamp", types: [.fighting], pokemonImage: "img_68", defImage: "IMG_2490"),
    Pokemon(id: 69, name: "bellsprout", types: [.grass, .poison], pokemonImage: "img_69", defImage: "IMG_2491"),
    Pokemon(id: 70, name: "weepinbell", types: [.grass, .poison], pokemonImage: "img_70", defImage: "IMG_2492"),
    Pokemon(id: 71, name: "victreebel", types: [.grass, .poison], pokemonImage: "img_71", defImage: "IMG_2493"),
    Pokemon(id: 72, name: "tentacool", types: [.water, .poison], pokemonImage: "img_72", defImage: "IMG_2494"),
    Pokemon(id: 73, name: "tentacruel", types: [.water, .poison], pokemonImage: "img_73", defImage: "IMG_2495"),
    Pokemon(id: 74, name: "geodude", types: [.rock, .ground], pokemonImage: "img_74", defImage: "IMG_2500"),
    Pokemon(id: 75, name: "graveler", types: [.rock, .ground], pokemonImage: "img_75", defImage: "IMG_2501"),
    Pokemon(id: 76, name: "golem", types: [.rock, .ground], pokemonImage: "img_76", defImage: "IMG_2502"),
    Pokemon(id: 77, name: "ponyta", types: [.fire], pokemonImage: "img_77", defImage: "IMG_2503"),
    Pokemon(id: 78, name: "rapidash", types: [.fire], pokemonImage: "img_78", defImage: "IMG_2504"),
    Pokemon(id: 79, name: "slowpoke", types: [.water, .psychic], pokemonImage: "img_79", defImage: "IMG_2505"),
    Pokemon(id: 80, name: "slowbro", types: [.water, .psychic], pokemonImage: "img_80", defImage: "IMG_2506"),
    Pokemon(id: 81, name: "magnemite", types: [.electric, .steel], pokemonImage: "img_81", defImage: "IMG_2507"),
    Pokemon(id: 82, name: "magneton", types: [.electric, .steel], pokemonImage: "img_82", defImage: "IMG_2508"),
    Pokemon(id: 83, name: "farfetchd", types: [.normal, .flying], pokemonImage: "img_83", defImage: "IMG_2509"),
    Pokemon(id: 84, name: "doduo", types: [.normal, .flying], pokemonImage: "img_84", defImage: "IMG_2510"),
    Pokemon(id: 85, name: "dodrio", types: [.normal, .flying], pokemonImage: "img_85", defImage: "IMG_2511"),
    Pokemon(id: 86, name: "seel", types: [.water], pokemonImage: "img_86", defImage: "IMG_2512"),
    Pokemon(id: 87, name: "dewgong", types: [.water, .ice], pokemonImage: "img_87", defImage: "IMG_2513"),
    Pokemon(id: 88, name: "grimer", types: [.poison], pokemonImage: "img_88", defImage: "IMG_2514"),
    Pokemon(id: 89, name: "muk", types: [.poison], pokemonImage: "img_89", defImage: "IMG_2515"),
    Pokemon(id: 90, name: "shellder", types: [.water], pokemonImage: "img_90", defImage: "IMG_2516"),
    Pokemon(id: 91, name: "cloyster", types: [.water, .ice], pokemonImage: "img_91", defImage: "IMG_2517"),
    Pokemon(id: 92, name: "gastly", types: [.ghost, .poison], pokemonImage: "img_92", defImage: "IMG_2518"),
    Pokemon(id: 93, name: "haunter", types: [.ghost, .poison], pokemonImage: "img_93", defImage: "IMG_2519"),
    Pokemon(id: 94, name: "gengar", types: [.ghost, .poison], pokemonImage: "img_94", defImage: "IMG_2520"),
    Pokemon(id: 95, name: "onix", types: [.rock, .ground], pokemonImage: "img_95", defImage: "IMG_2521"),
    Pokemon(id: 96, name: "drowzee", types: [.psychic], pokemonImage: "img_96", defImage: "IMG_2522"),
    Pokemon(id: 97, name: "hypno", types: [.psychic], pokemonImage: "img_97", defImage: "IMG_2523"),
    Pokemon(id: 98, name: "krabby", types: [.water], pokemonImage: "img_98", defImage: "IMG_2524"),
    Pokemon(id: 99, name: "kingler", types: [.water], pokemonImage: "img_99", defImage: "IMG_2525"),
    Pokemon(id: 100, name: "voltorb", types: [.electric], pokemonImage: "img_100", defImage: "IMG_2526"),
    Pokemon(id: 101, name: "electrode", types: [.electric], pokemonImage: "img_101", defImage: "IMG_2527"),
    Pokemon(id: 102, name: "exeggcute", types: [.grass, .psychic], pokemonImage: "img_102", defImage: "IMG_2528"),
    Pokemon(id: 103, name: "exeggutor", types: [.grass, .psychic], pokemonImage: "img_103", defImage: "IMG_2529"),
    Pokemon(id: 104, name: "cubone", types: [.ground], pokemonImage: "img_104", defImage: "IMG_2530"),
    Pokemon(id: 105, name: "marowak", types: [.ground], pokemonImage: "img_105", defImage: "IMG_2531"),
    Pokemon(id: 106, name: "hitmonlee", types: [.fighting], pokemonImage: "img_106", defImage: "IMG_2532"),
    Pokemon(id: 107, name: "hitmonchan", types: [.fighting], pokemonImage: "img_107", defImage: "IMG_2533"),
    Pokemon(id: 108, name: "lickitung", types: [.normal], pokemonImage: "img_108", defImage: "IMG_2534"),
    Pokemon(id: 109, name: "koffing", types: [.poison], pokemonImage: "img_109", defImage: "IMG_2535"),
    Pokemon(id: 110, name: "weezing", types: [.poison], pokemonImage: "img_110", defImage: "IMG_2536"),
    Pokemon(id: 111, name: "rhyhorn", types: [.ground, .rock], pokemonImage: "img_111", defImage: "IMG_2537"),
    Pokemon(id: 112, name: "rhydon", types: [.ground, .rock], pokemonImage: "img_112", defImage: "IMG_2538"),
    Pokemon(id: 113, name: "chansey", types: [.normal], pokemonImage: "img_113", defImage: "IMG_2539"),
    Pokemon(id: 114, name: "tangela", types: [.grass], pokemonImage: "img_114", defImage: "IMG_2540"),
    Pokemon(id: 115, name: "kangaskhan", types: [.normal], pokemonImage: "img_115", defImage: "IMG_2541"),
    Pokemon(id: 116, name: "horsea", types: [.water], pokemonImage: "img_116", defImage: "IMG_2542"),
    Pokemon(id: 117, name: "seadra", types: [.water], pokemonImage: "img_117", defImage: "IMG_2543"),
    Pokemon(id: 118, name: "goldeen", types: [.water], pokemonImage: "img_118", defImage: "IMG_2544"),
    Pokemon(id: 119, name: "seaking", types: [.water], pokemonImage: "img_119", defImage: "IMG_2545"),
    Pokemon(id: 120, name: "staryu", types: [.water], pokemonImage: "img_120", defImage: "IMG_2546"),
    Pokemon(id: 121, name: "starmie", types: [.water, .psychic], pokemonImage: "img_121", defImage: "IMG_2547"),
    Pokemon(id: 122, name: "mr-mime", types: [.psychic, .fairy], pokemonImage: "img_122", defImage: "IMG_2548"),
    Pokemon(id: 123, name: "scyther", types: [.bug, .flying], pokemonImage: "img_123", defImage: "IMG_2549"),
    Pokemon(id: 124, name: "jynx", types: [.ice, .psychic], pokemonImage: "img_124", defImage: "IMG_2550"),
    Pokemon(id: 125, name: "electabuzz", types: [.electric], pokemonImage: "img_125", defImage: "IMG_2551"),
    Pokemon(id: 126, name: "magmar", types: [.fire], pokemonImage: "img_126", defImage: "IMG_2552"),
    Pokemon(id: 127, name: "pinsir", types: [.bug], pokemonImage: "img_127", defImage: "IMG_2553"),
    Pokemon(id: 128, name: "tauros", types: [.normal], pokemonImage: "img_128", defImage: "IMG_2554"),
    Pokemon(id: 129, name: "magikarp", types: [.water], pokemonImage: "img_129", defImage: "IMG_2555"),
    Pokemon(id: 130, name: "gyarados", types: [.water, .flying], pokemonImage: "img_130", defImage: "IMG_2556"),
    Pokemon(id: 131, name: "lapras", types: [.water, .ice], pokemonImage: "img_131", defImage: "IMG_2557"),
    Pokemon(id: 132, name: "ditto", types: [.normal], pokemonImage: "img_132", defImage: "IMG_2558"),
    Pokemon(id: 133, name: "eevee", types: [.normal], pokemonImage: "img_133", defImage: "IMG_2559"),
    Pokemon(id: 134, name: "vaporeon", types: [.water], pokemonImage: "img_134", defImage: "IMG_2560"),
    Pokemon(id: 135, name: "jolteon", types: [.electric], pokemonImage: "img_135", defImage: "IMG_2561"),
    Pokemon(id: 136, name: "flareon", types: [.fire], pokemonImage: "img_136", defImage: "IMG_2562"),
    Pokemon(id: 137, name: "porygon", types: [.normal], pokemonImage: "img_137", defImage: "IMG_2563"),
    Pokemon(id: 138, name: "omanyte", types: [.rock, .water], pokemonImage: "img_138", defImage: "IMG_2564"),
    Pokemon(id: 139, name: "omastar", types: [.rock, .water], pokemonImage: "img_139", defImage: "IMG_2565"),
    Pokemon(id: 140, name: "kabuto", types: [.rock, .water], pokemonImage: "img_140", defImage: "IMG_2566"),
    Pokemon(id: 141, name: "kabutops", types: [.rock, .water], pokemonImage: "img_141", defImage: "IMG_2567"),
    Pokemon(id: 142, name: "aerodactyl", types: [.rock, .flying], pokemonImage: "img_142", defImage: "IMG_2568"),
    Pokemon(id: 143, name: "snorlax", types: [.normal], pokemonImage: "img_143", defImage: "IMG_2569"),
    Pokemon(id: 144, name: "articuno", types: [.ice, .flying], pokemonImage: "img_144", defImage: "IMG_2570"),
    Pokemon(id: 145, name: "zapdos", types: [.electric, .flying], pokemonImage: "img_145", defImage: "IMG_2571"),
    Pokemon(id: 146, name: "moltres", types: [.fire, .flying], pokemonImage: "img_146", defImage: "IMG_2572"),
    Pokemon(id: 147, name: "dratini", types: [.dragon], pokemonImage: "img_147", defImage: "IMG_2573"),
    Pokemon(id: 148, name: "dragonair", types: [.dragon], pokemonImage: "img_148", defImage: "IMG_2574"),
    Pokemon(id: 149, name: "dragonite", types: [.dragon, .flying], pokemonImage: "img_149", defImage: "IMG_2575"),
    Pokemon(id: 150, name: "mewtwo", types: [.psychic], pokemonImage: "img_150", defImage: "IMG_2576"),
    Pokemon(id: 151, name: "mew", types: [.psychic], pokemonImage: "img_151", defImage: "IMG_2577"),
]

